// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	models "github.com/c360dev/sawmint/models"
)

// GetBatchesBatchIDHandlerFunc turns a function with the right signature into a get batches batch ID handler
type GetBatchesBatchIDHandlerFunc func(GetBatchesBatchIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBatchesBatchIDHandlerFunc) Handle(params GetBatchesBatchIDParams) middleware.Responder {
	return fn(params)
}

// GetBatchesBatchIDHandler interface for that can handle valid get batches batch ID params
type GetBatchesBatchIDHandler interface {
	Handle(GetBatchesBatchIDParams) middleware.Responder
}

// NewGetBatchesBatchID creates a new http.Handler for the get batches batch ID operation
func NewGetBatchesBatchID(ctx *middleware.Context, handler GetBatchesBatchIDHandler) *GetBatchesBatchID {
	return &GetBatchesBatchID{Context: ctx, Handler: handler}
}

/*GetBatchesBatchID swagger:route GET /batches/{batch_id} getBatchesBatchId

Fetches a particular batch

*/
type GetBatchesBatchID struct {
	Context *middleware.Context
	Handler GetBatchesBatchIDHandler
}

func (o *GetBatchesBatchID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetBatchesBatchIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetBatchesBatchIDOKBody get batches batch ID o k body
// swagger:model GetBatchesBatchIDOKBody
type GetBatchesBatchIDOKBody struct {

	// data
	Data *models.Batch `json:"data,omitempty"`

	// head
	Head models.Head `json:"head,omitempty"`

	// link
	Link models.Link `json:"link,omitempty"`
}

// Validate validates this get batches batch ID o k body
func (o *GetBatchesBatchIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateHead(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLink(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetBatchesBatchIDOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getBatchesBatchIdOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

func (o *GetBatchesBatchIDOKBody) validateHead(formats strfmt.Registry) error {

	if swag.IsZero(o.Head) { // not required
		return nil
	}

	if err := o.Head.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("getBatchesBatchIdOK" + "." + "head")
		}
		return err
	}

	return nil
}

func (o *GetBatchesBatchIDOKBody) validateLink(formats strfmt.Registry) error {

	if swag.IsZero(o.Link) { // not required
		return nil
	}

	if err := o.Link.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("getBatchesBatchIdOK" + "." + "link")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetBatchesBatchIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetBatchesBatchIDOKBody) UnmarshalBinary(b []byte) error {
	var res GetBatchesBatchIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
