// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBlocksBlockIDParams creates a new GetBlocksBlockIDParams object
// no default values defined in spec.
func NewGetBlocksBlockIDParams() GetBlocksBlockIDParams {

	return GetBlocksBlockIDParams{}
}

// GetBlocksBlockIDParams contains all the bound params for the get blocks block ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetBlocksBlockID
type GetBlocksBlockIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Block id
	  Required: true
	  In: path
	*/
	BlockID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetBlocksBlockIDParams() beforehand.
func (o *GetBlocksBlockIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rBlockID, rhkBlockID, _ := route.Params.GetOK("block_id")
	if err := o.bindBlockID(rBlockID, rhkBlockID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindBlockID binds and validates parameter BlockID from path.
func (o *GetBlocksBlockIDParams) bindBlockID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.BlockID = raw

	return nil
}
