// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	models "github.com/c360dev/sawmint/models"
)

// GetBlocksBlockIDHandlerFunc turns a function with the right signature into a get blocks block ID handler
type GetBlocksBlockIDHandlerFunc func(GetBlocksBlockIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBlocksBlockIDHandlerFunc) Handle(params GetBlocksBlockIDParams) middleware.Responder {
	return fn(params)
}

// GetBlocksBlockIDHandler interface for that can handle valid get blocks block ID params
type GetBlocksBlockIDHandler interface {
	Handle(GetBlocksBlockIDParams) middleware.Responder
}

// NewGetBlocksBlockID creates a new http.Handler for the get blocks block ID operation
func NewGetBlocksBlockID(ctx *middleware.Context, handler GetBlocksBlockIDHandler) *GetBlocksBlockID {
	return &GetBlocksBlockID{Context: ctx, Handler: handler}
}

/*GetBlocksBlockID swagger:route GET /blocks/{block_id} getBlocksBlockId

Fetches a particular block

*/
type GetBlocksBlockID struct {
	Context *middleware.Context
	Handler GetBlocksBlockIDHandler
}

func (o *GetBlocksBlockID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetBlocksBlockIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetBlocksBlockIDOKBody get blocks block ID o k body
// swagger:model GetBlocksBlockIDOKBody
type GetBlocksBlockIDOKBody struct {

	// data
	Data *models.Block `json:"data,omitempty"`

	// head
	Head models.Head `json:"head,omitempty"`

	// link
	Link models.Link `json:"link,omitempty"`
}

// Validate validates this get blocks block ID o k body
func (o *GetBlocksBlockIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateHead(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLink(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetBlocksBlockIDOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getBlocksBlockIdOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

func (o *GetBlocksBlockIDOKBody) validateHead(formats strfmt.Registry) error {

	if swag.IsZero(o.Head) { // not required
		return nil
	}

	if err := o.Head.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("getBlocksBlockIdOK" + "." + "head")
		}
		return err
	}

	return nil
}

func (o *GetBlocksBlockIDOKBody) validateLink(formats strfmt.Registry) error {

	if swag.IsZero(o.Link) { // not required
		return nil
	}

	if err := o.Link.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("getBlocksBlockIdOK" + "." + "link")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetBlocksBlockIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetBlocksBlockIDOKBody) UnmarshalBinary(b []byte) error {
	var res GetBlocksBlockIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
