// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	models "github.com/faddat/sawmint/models"
)

// GetStateHandlerFunc turns a function with the right signature into a get state handler
type GetStateHandlerFunc func(GetStateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetStateHandlerFunc) Handle(params GetStateParams) middleware.Responder {
	return fn(params)
}

// GetStateHandler interface for that can handle valid get state params
type GetStateHandler interface {
	Handle(GetStateParams) middleware.Responder
}

// NewGetState creates a new http.Handler for the get state operation
func NewGetState(ctx *middleware.Context, handler GetStateHandler) *GetState {
	return &GetState{Context: ctx, Handler: handler}
}

/*GetState swagger:route GET /state getState

Fetches the data for the current state

Fetches a paginated list of entries for the current state, or relative to a particular head block. Using the `address` filter parameter will narrow the list to any entries that have an address beginning with the characters specified.
Note that the partial address in `address` parameter should have even  number of hecadeximal characters (i.e., complete bytes).


*/
type GetState struct {
	Context *middleware.Context
	Handler GetStateHandler
}

func (o *GetState) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetStateParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetStateOKBody get state o k body
// swagger:model GetStateOKBody
type GetStateOKBody struct {

	// data
	Data []*models.Entry `json:"data"`

	// head
	Head models.Head `json:"head,omitempty"`

	// link
	Link models.Link `json:"link,omitempty"`

	// paging
	Paging *models.Paging `json:"paging,omitempty"`
}

// Validate validates this get state o k body
func (o *GetStateOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateHead(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLink(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePaging(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetStateOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getStateOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetStateOKBody) validateHead(formats strfmt.Registry) error {

	if swag.IsZero(o.Head) { // not required
		return nil
	}

	if err := o.Head.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("getStateOK" + "." + "head")
		}
		return err
	}

	return nil
}

func (o *GetStateOKBody) validateLink(formats strfmt.Registry) error {

	if swag.IsZero(o.Link) { // not required
		return nil
	}

	if err := o.Link.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("getStateOK" + "." + "link")
		}
		return err
	}

	return nil
}

func (o *GetStateOKBody) validatePaging(formats strfmt.Registry) error {

	if swag.IsZero(o.Paging) { // not required
		return nil
	}

	if o.Paging != nil {
		if err := o.Paging.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getStateOK" + "." + "paging")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetStateOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetStateOKBody) UnmarshalBinary(b []byte) error {
	var res GetStateOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
