// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	models "github.com/c360dev/sawmint/models"
)

// GetPeersHandlerFunc turns a function with the right signature into a get peers handler
type GetPeersHandlerFunc func(GetPeersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPeersHandlerFunc) Handle(params GetPeersParams) middleware.Responder {
	return fn(params)
}

// GetPeersHandler interface for that can handle valid get peers params
type GetPeersHandler interface {
	Handle(GetPeersParams) middleware.Responder
}

// NewGetPeers creates a new http.Handler for the get peers operation
func NewGetPeers(ctx *middleware.Context, handler GetPeersHandler) *GetPeers {
	return &GetPeers{Context: ctx, Handler: handler}
}

/*GetPeers swagger:route GET /peers getPeers

Fetches the endpoints of the authorized peers of the validator

*/
type GetPeers struct {
	Context *middleware.Context
	Handler GetPeersHandler
}

func (o *GetPeers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPeersParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetPeersOKBody get peers o k body
// swagger:model GetPeersOKBody
type GetPeersOKBody struct {

	// data
	Data []string `json:"data"`

	// link
	Link models.Link `json:"link,omitempty"`
}

// Validate validates this get peers o k body
func (o *GetPeersOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLink(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPeersOKBody) validateLink(formats strfmt.Registry) error {

	if swag.IsZero(o.Link) { // not required
		return nil
	}

	if err := o.Link.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("getPeersOK" + "." + "link")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetPeersOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPeersOKBody) UnmarshalBinary(b []byte) error {
	var res GetPeersOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
