// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/faddat/sawmint/models"
)

// GetBlocksBlockIDOKCode is the HTTP code returned for type GetBlocksBlockIDOK
const GetBlocksBlockIDOKCode int = 200

/*GetBlocksBlockIDOK Successfully retrieved block

swagger:response getBlocksBlockIdOK
*/
type GetBlocksBlockIDOK struct {

	/*
	  In: Body
	*/
	Payload *GetBlocksBlockIDOKBody `json:"body,omitempty"`
}

// NewGetBlocksBlockIDOK creates GetBlocksBlockIDOK with default headers values
func NewGetBlocksBlockIDOK() *GetBlocksBlockIDOK {

	return &GetBlocksBlockIDOK{}
}

// WithPayload adds the payload to the get blocks block Id o k response
func (o *GetBlocksBlockIDOK) WithPayload(payload *GetBlocksBlockIDOKBody) *GetBlocksBlockIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get blocks block Id o k response
func (o *GetBlocksBlockIDOK) SetPayload(payload *GetBlocksBlockIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlocksBlockIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBlocksBlockIDBadRequestCode is the HTTP code returned for type GetBlocksBlockIDBadRequest
const GetBlocksBlockIDBadRequestCode int = 400

/*GetBlocksBlockIDBadRequest Request was malformed

swagger:response getBlocksBlockIdBadRequest
*/
type GetBlocksBlockIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBlocksBlockIDBadRequest creates GetBlocksBlockIDBadRequest with default headers values
func NewGetBlocksBlockIDBadRequest() *GetBlocksBlockIDBadRequest {

	return &GetBlocksBlockIDBadRequest{}
}

// WithPayload adds the payload to the get blocks block Id bad request response
func (o *GetBlocksBlockIDBadRequest) WithPayload(payload *models.Error) *GetBlocksBlockIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get blocks block Id bad request response
func (o *GetBlocksBlockIDBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlocksBlockIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBlocksBlockIDNotFoundCode is the HTTP code returned for type GetBlocksBlockIDNotFound
const GetBlocksBlockIDNotFoundCode int = 404

/*GetBlocksBlockIDNotFound Address or id did not match any resource

swagger:response getBlocksBlockIdNotFound
*/
type GetBlocksBlockIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBlocksBlockIDNotFound creates GetBlocksBlockIDNotFound with default headers values
func NewGetBlocksBlockIDNotFound() *GetBlocksBlockIDNotFound {

	return &GetBlocksBlockIDNotFound{}
}

// WithPayload adds the payload to the get blocks block Id not found response
func (o *GetBlocksBlockIDNotFound) WithPayload(payload *models.Error) *GetBlocksBlockIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get blocks block Id not found response
func (o *GetBlocksBlockIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlocksBlockIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBlocksBlockIDInternalServerErrorCode is the HTTP code returned for type GetBlocksBlockIDInternalServerError
const GetBlocksBlockIDInternalServerErrorCode int = 500

/*GetBlocksBlockIDInternalServerError Something went wrong within the validator

swagger:response getBlocksBlockIdInternalServerError
*/
type GetBlocksBlockIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBlocksBlockIDInternalServerError creates GetBlocksBlockIDInternalServerError with default headers values
func NewGetBlocksBlockIDInternalServerError() *GetBlocksBlockIDInternalServerError {

	return &GetBlocksBlockIDInternalServerError{}
}

// WithPayload adds the payload to the get blocks block Id internal server error response
func (o *GetBlocksBlockIDInternalServerError) WithPayload(payload *models.Error) *GetBlocksBlockIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get blocks block Id internal server error response
func (o *GetBlocksBlockIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlocksBlockIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBlocksBlockIDServiceUnavailableCode is the HTTP code returned for type GetBlocksBlockIDServiceUnavailable
const GetBlocksBlockIDServiceUnavailableCode int = 503

/*GetBlocksBlockIDServiceUnavailable API is unable to reach the validator

swagger:response getBlocksBlockIdServiceUnavailable
*/
type GetBlocksBlockIDServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBlocksBlockIDServiceUnavailable creates GetBlocksBlockIDServiceUnavailable with default headers values
func NewGetBlocksBlockIDServiceUnavailable() *GetBlocksBlockIDServiceUnavailable {

	return &GetBlocksBlockIDServiceUnavailable{}
}

// WithPayload adds the payload to the get blocks block Id service unavailable response
func (o *GetBlocksBlockIDServiceUnavailable) WithPayload(payload *models.Error) *GetBlocksBlockIDServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get blocks block Id service unavailable response
func (o *GetBlocksBlockIDServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlocksBlockIDServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
