// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/faddat/sawmint/models"
)

// GetBatchesOKCode is the HTTP code returned for type GetBatchesOK
const GetBatchesOKCode int = 200

/*GetBatchesOK Successfully retrieved batches

swagger:response getBatchesOK
*/
type GetBatchesOK struct {

	/*
	  In: Body
	*/
	Payload *GetBatchesOKBody `json:"body,omitempty"`
}

// NewGetBatchesOK creates GetBatchesOK with default headers values
func NewGetBatchesOK() *GetBatchesOK {

	return &GetBatchesOK{}
}

// WithPayload adds the payload to the get batches o k response
func (o *GetBatchesOK) WithPayload(payload *GetBatchesOKBody) *GetBatchesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get batches o k response
func (o *GetBatchesOK) SetPayload(payload *GetBatchesOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBatchesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBatchesBadRequestCode is the HTTP code returned for type GetBatchesBadRequest
const GetBatchesBadRequestCode int = 400

/*GetBatchesBadRequest Request was malformed

swagger:response getBatchesBadRequest
*/
type GetBatchesBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBatchesBadRequest creates GetBatchesBadRequest with default headers values
func NewGetBatchesBadRequest() *GetBatchesBadRequest {

	return &GetBatchesBadRequest{}
}

// WithPayload adds the payload to the get batches bad request response
func (o *GetBatchesBadRequest) WithPayload(payload *models.Error) *GetBatchesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get batches bad request response
func (o *GetBatchesBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBatchesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBatchesInternalServerErrorCode is the HTTP code returned for type GetBatchesInternalServerError
const GetBatchesInternalServerErrorCode int = 500

/*GetBatchesInternalServerError Something went wrong within the validator

swagger:response getBatchesInternalServerError
*/
type GetBatchesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBatchesInternalServerError creates GetBatchesInternalServerError with default headers values
func NewGetBatchesInternalServerError() *GetBatchesInternalServerError {

	return &GetBatchesInternalServerError{}
}

// WithPayload adds the payload to the get batches internal server error response
func (o *GetBatchesInternalServerError) WithPayload(payload *models.Error) *GetBatchesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get batches internal server error response
func (o *GetBatchesInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBatchesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBatchesServiceUnavailableCode is the HTTP code returned for type GetBatchesServiceUnavailable
const GetBatchesServiceUnavailableCode int = 503

/*GetBatchesServiceUnavailable API is unable to reach the validator

swagger:response getBatchesServiceUnavailable
*/
type GetBatchesServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBatchesServiceUnavailable creates GetBatchesServiceUnavailable with default headers values
func NewGetBatchesServiceUnavailable() *GetBatchesServiceUnavailable {

	return &GetBatchesServiceUnavailable{}
}

// WithPayload adds the payload to the get batches service unavailable response
func (o *GetBatchesServiceUnavailable) WithPayload(payload *models.Error) *GetBatchesServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get batches service unavailable response
func (o *GetBatchesServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBatchesServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
