// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/c360dev/sawmint/models"
)

// GetReceiptsOKCode is the HTTP code returned for type GetReceiptsOK
const GetReceiptsOKCode int = 200

/*GetReceiptsOK Successfully retrieved transaction receipts

swagger:response getReceiptsOK
*/
type GetReceiptsOK struct {

	/*
	  In: Body
	*/
	Payload *GetReceiptsOKBody `json:"body,omitempty"`
}

// NewGetReceiptsOK creates GetReceiptsOK with default headers values
func NewGetReceiptsOK() *GetReceiptsOK {

	return &GetReceiptsOK{}
}

// WithPayload adds the payload to the get receipts o k response
func (o *GetReceiptsOK) WithPayload(payload *GetReceiptsOKBody) *GetReceiptsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get receipts o k response
func (o *GetReceiptsOK) SetPayload(payload *GetReceiptsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReceiptsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetReceiptsBadRequestCode is the HTTP code returned for type GetReceiptsBadRequest
const GetReceiptsBadRequestCode int = 400

/*GetReceiptsBadRequest Request was malformed

swagger:response getReceiptsBadRequest
*/
type GetReceiptsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetReceiptsBadRequest creates GetReceiptsBadRequest with default headers values
func NewGetReceiptsBadRequest() *GetReceiptsBadRequest {

	return &GetReceiptsBadRequest{}
}

// WithPayload adds the payload to the get receipts bad request response
func (o *GetReceiptsBadRequest) WithPayload(payload *models.Error) *GetReceiptsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get receipts bad request response
func (o *GetReceiptsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReceiptsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetReceiptsInternalServerErrorCode is the HTTP code returned for type GetReceiptsInternalServerError
const GetReceiptsInternalServerErrorCode int = 500

/*GetReceiptsInternalServerError Something went wrong within the validator

swagger:response getReceiptsInternalServerError
*/
type GetReceiptsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetReceiptsInternalServerError creates GetReceiptsInternalServerError with default headers values
func NewGetReceiptsInternalServerError() *GetReceiptsInternalServerError {

	return &GetReceiptsInternalServerError{}
}

// WithPayload adds the payload to the get receipts internal server error response
func (o *GetReceiptsInternalServerError) WithPayload(payload *models.Error) *GetReceiptsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get receipts internal server error response
func (o *GetReceiptsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReceiptsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetReceiptsServiceUnavailableCode is the HTTP code returned for type GetReceiptsServiceUnavailable
const GetReceiptsServiceUnavailableCode int = 503

/*GetReceiptsServiceUnavailable API is unable to reach the validator

swagger:response getReceiptsServiceUnavailable
*/
type GetReceiptsServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetReceiptsServiceUnavailable creates GetReceiptsServiceUnavailable with default headers values
func NewGetReceiptsServiceUnavailable() *GetReceiptsServiceUnavailable {

	return &GetReceiptsServiceUnavailable{}
}

// WithPayload adds the payload to the get receipts service unavailable response
func (o *GetReceiptsServiceUnavailable) WithPayload(payload *models.Error) *GetReceiptsServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get receipts service unavailable response
func (o *GetReceiptsServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReceiptsServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
