// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetStateAddressParams creates a new GetStateAddressParams object
// with the default values initialized.
func NewGetStateAddressParams() GetStateAddressParams {

	var (
		// initialize parameters with default values

		headDefault = string("latest")
	)

	return GetStateAddressParams{
		Head: &headDefault,
	}
}

// GetStateAddressParams contains all the bound params for the get state address operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetStateAddress
type GetStateAddressParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Radix address of a leaf
	  Required: true
	  In: path
	*/
	Address string
	/*Index or id of head block
	  In: query
	  Default: "latest"
	*/
	Head *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetStateAddressParams() beforehand.
func (o *GetStateAddressParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	rAddress, rhkAddress, _ := route.Params.GetOK("address")
	if err := o.bindAddress(rAddress, rhkAddress, route.Formats); err != nil {
		res = append(res, err)
	}

	qHead, qhkHead, _ := qs.GetOK("head")
	if err := o.bindHead(qHead, qhkHead, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAddress binds and validates parameter Address from path.
func (o *GetStateAddressParams) bindAddress(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Address = raw

	return nil
}

// bindHead binds and validates parameter Head from query.
func (o *GetStateAddressParams) bindHead(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetStateAddressParams()
		return nil
	}

	o.Head = &raw

	return nil
}
