// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/faddat/sawmint/models"
)

// NewPostBatchesParams creates a new PostBatchesParams object
// no default values defined in spec.
func NewPostBatchesParams() PostBatchesParams {

	return PostBatchesParams{}
}

// PostBatchesParams contains all the bound params for the post batches operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostBatches
type PostBatchesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*A binary encoded protobuf BatchList
	  Required: true
	  In: body
	*/
	BatchList *models.BatchList
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostBatchesParams() beforehand.
func (o *PostBatchesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.BatchList
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("batchList", "body"))
			} else {
				res = append(res, errors.NewParseError("batchList", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.BatchList = &body
			}
		}
	} else {
		res = append(res, errors.Required("batchList", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
