// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	models "github.com/c360dev/sawmint/models"
)

// PostBatchesHandlerFunc turns a function with the right signature into a post batches handler
type PostBatchesHandlerFunc func(PostBatchesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostBatchesHandlerFunc) Handle(params PostBatchesParams) middleware.Responder {
	return fn(params)
}

// PostBatchesHandler interface for that can handle valid post batches params
type PostBatchesHandler interface {
	Handle(PostBatchesParams) middleware.Responder
}

// NewPostBatches creates a new http.Handler for the post batches operation
func NewPostBatches(ctx *middleware.Context, handler PostBatchesHandler) *PostBatches {
	return &PostBatches{Context: ctx, Handler: handler}
}

/*PostBatches swagger:route POST /batches postBatches

Sends a BatchList to the validator

Accepts a protobuf formatted `BatchList` as an octet-stream binary
file and submits it to the validator to be committed.

The API will return immediately with a status of `202`. There will be
no `data` object, only a `link` to a `/batch_statuses` endpoint to be
polled to check the status of submitted batches.


*/
type PostBatches struct {
	Context *middleware.Context
	Handler PostBatchesHandler
}

func (o *PostBatches) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostBatchesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostBatchesAcceptedBody post batches accepted body
// swagger:model PostBatchesAcceptedBody
type PostBatchesAcceptedBody struct {

	// link
	Link models.Link `json:"link,omitempty"`
}

// Validate validates this post batches accepted body
func (o *PostBatchesAcceptedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLink(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostBatchesAcceptedBody) validateLink(formats strfmt.Registry) error {

	if swag.IsZero(o.Link) { // not required
		return nil
	}

	if err := o.Link.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("postBatchesAccepted" + "." + "link")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostBatchesAcceptedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostBatchesAcceptedBody) UnmarshalBinary(b []byte) error {
	var res PostBatchesAcceptedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
