// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewSawtoothRESTAPI creates a new SawtoothREST instance
func NewSawtoothRESTAPI(spec *loads.Document) *SawtoothRESTAPI {
	return &SawtoothRESTAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		BinConsumer:         runtime.ByteStreamConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		GetBatchStatusesHandler: GetBatchStatusesHandlerFunc(func(params GetBatchStatusesParams) middleware.Responder {
			return middleware.NotImplemented("operation GetBatchStatuses has not yet been implemented")
		}),
		GetBatchesHandler: GetBatchesHandlerFunc(func(params GetBatchesParams) middleware.Responder {
			return middleware.NotImplemented("operation GetBatches has not yet been implemented")
		}),
		GetBatchesBatchIDHandler: GetBatchesBatchIDHandlerFunc(func(params GetBatchesBatchIDParams) middleware.Responder {
			return middleware.NotImplemented("operation GetBatchesBatchID has not yet been implemented")
		}),
		GetBlocksHandler: GetBlocksHandlerFunc(func(params GetBlocksParams) middleware.Responder {
			return middleware.NotImplemented("operation GetBlocks has not yet been implemented")
		}),
		GetBlocksBlockIDHandler: GetBlocksBlockIDHandlerFunc(func(params GetBlocksBlockIDParams) middleware.Responder {
			return middleware.NotImplemented("operation GetBlocksBlockID has not yet been implemented")
		}),
		GetPeersHandler: GetPeersHandlerFunc(func(params GetPeersParams) middleware.Responder {
			return middleware.NotImplemented("operation GetPeers has not yet been implemented")
		}),
		GetReceiptsHandler: GetReceiptsHandlerFunc(func(params GetReceiptsParams) middleware.Responder {
			return middleware.NotImplemented("operation GetReceipts has not yet been implemented")
		}),
		GetStateHandler: GetStateHandlerFunc(func(params GetStateParams) middleware.Responder {
			return middleware.NotImplemented("operation GetState has not yet been implemented")
		}),
		GetStateAddressHandler: GetStateAddressHandlerFunc(func(params GetStateAddressParams) middleware.Responder {
			return middleware.NotImplemented("operation GetStateAddress has not yet been implemented")
		}),
		GetStatusHandler: GetStatusHandlerFunc(func(params GetStatusParams) middleware.Responder {
			return middleware.NotImplemented("operation GetStatus has not yet been implemented")
		}),
		GetTransactionsHandler: GetTransactionsHandlerFunc(func(params GetTransactionsParams) middleware.Responder {
			return middleware.NotImplemented("operation GetTransactions has not yet been implemented")
		}),
		GetTransactionsTransactionIDHandler: GetTransactionsTransactionIDHandlerFunc(func(params GetTransactionsTransactionIDParams) middleware.Responder {
			return middleware.NotImplemented("operation GetTransactionsTransactionID has not yet been implemented")
		}),
		PostBatchStatusesHandler: PostBatchStatusesHandlerFunc(func(params PostBatchStatusesParams) middleware.Responder {
			return middleware.NotImplemented("operation PostBatchStatuses has not yet been implemented")
		}),
		PostBatchesHandler: PostBatchesHandlerFunc(func(params PostBatchesParams) middleware.Responder {
			return middleware.NotImplemented("operation PostBatches has not yet been implemented")
		}),
		PostReceiptsHandler: PostReceiptsHandlerFunc(func(params PostReceiptsParams) middleware.Responder {
			return middleware.NotImplemented("operation PostReceipts has not yet been implemented")
		}),
	}
}

/*SawtoothRESTAPI _This HTTP pragmatic REST API is built on top of Sawtooth's
existing ZMQ/Protobuf infrastructure, simplifying client
interaction with the blockchain by exposing endpoints that
use common HTTP/JSON standards._
*/
type SawtoothRESTAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer
	// BinConsumer registers a consumer for a "application/octet-stream" mime type
	BinConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// GetBatchStatusesHandler sets the operation handler for the get batch statuses operation
	GetBatchStatusesHandler GetBatchStatusesHandler
	// GetBatchesHandler sets the operation handler for the get batches operation
	GetBatchesHandler GetBatchesHandler
	// GetBatchesBatchIDHandler sets the operation handler for the get batches batch ID operation
	GetBatchesBatchIDHandler GetBatchesBatchIDHandler
	// GetBlocksHandler sets the operation handler for the get blocks operation
	GetBlocksHandler GetBlocksHandler
	// GetBlocksBlockIDHandler sets the operation handler for the get blocks block ID operation
	GetBlocksBlockIDHandler GetBlocksBlockIDHandler
	// GetPeersHandler sets the operation handler for the get peers operation
	GetPeersHandler GetPeersHandler
	// GetReceiptsHandler sets the operation handler for the get receipts operation
	GetReceiptsHandler GetReceiptsHandler
	// GetStateHandler sets the operation handler for the get state operation
	GetStateHandler GetStateHandler
	// GetStateAddressHandler sets the operation handler for the get state address operation
	GetStateAddressHandler GetStateAddressHandler
	// GetStatusHandler sets the operation handler for the get status operation
	GetStatusHandler GetStatusHandler
	// GetTransactionsHandler sets the operation handler for the get transactions operation
	GetTransactionsHandler GetTransactionsHandler
	// GetTransactionsTransactionIDHandler sets the operation handler for the get transactions transaction ID operation
	GetTransactionsTransactionIDHandler GetTransactionsTransactionIDHandler
	// PostBatchStatusesHandler sets the operation handler for the post batch statuses operation
	PostBatchStatusesHandler PostBatchStatusesHandler
	// PostBatchesHandler sets the operation handler for the post batches operation
	PostBatchesHandler PostBatchesHandler
	// PostReceiptsHandler sets the operation handler for the post receipts operation
	PostReceiptsHandler PostReceiptsHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *SawtoothRESTAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *SawtoothRESTAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *SawtoothRESTAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *SawtoothRESTAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *SawtoothRESTAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *SawtoothRESTAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *SawtoothRESTAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the SawtoothRESTAPI
func (o *SawtoothRESTAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.BinConsumer == nil {
		unregistered = append(unregistered, "BinConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.GetBatchStatusesHandler == nil {
		unregistered = append(unregistered, "GetBatchStatusesHandler")
	}

	if o.GetBatchesHandler == nil {
		unregistered = append(unregistered, "GetBatchesHandler")
	}

	if o.GetBatchesBatchIDHandler == nil {
		unregistered = append(unregistered, "GetBatchesBatchIDHandler")
	}

	if o.GetBlocksHandler == nil {
		unregistered = append(unregistered, "GetBlocksHandler")
	}

	if o.GetBlocksBlockIDHandler == nil {
		unregistered = append(unregistered, "GetBlocksBlockIDHandler")
	}

	if o.GetPeersHandler == nil {
		unregistered = append(unregistered, "GetPeersHandler")
	}

	if o.GetReceiptsHandler == nil {
		unregistered = append(unregistered, "GetReceiptsHandler")
	}

	if o.GetStateHandler == nil {
		unregistered = append(unregistered, "GetStateHandler")
	}

	if o.GetStateAddressHandler == nil {
		unregistered = append(unregistered, "GetStateAddressHandler")
	}

	if o.GetStatusHandler == nil {
		unregistered = append(unregistered, "GetStatusHandler")
	}

	if o.GetTransactionsHandler == nil {
		unregistered = append(unregistered, "GetTransactionsHandler")
	}

	if o.GetTransactionsTransactionIDHandler == nil {
		unregistered = append(unregistered, "GetTransactionsTransactionIDHandler")
	}

	if o.PostBatchStatusesHandler == nil {
		unregistered = append(unregistered, "PostBatchStatusesHandler")
	}

	if o.PostBatchesHandler == nil {
		unregistered = append(unregistered, "PostBatchesHandler")
	}

	if o.PostReceiptsHandler == nil {
		unregistered = append(unregistered, "PostReceiptsHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *SawtoothRESTAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *SawtoothRESTAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *SawtoothRESTAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *SawtoothRESTAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		case "application/octet-stream":
			result["application/octet-stream"] = o.BinConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *SawtoothRESTAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *SawtoothRESTAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the sawtooth r e s t API
func (o *SawtoothRESTAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *SawtoothRESTAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/batch_statuses"] = NewGetBatchStatuses(o.context, o.GetBatchStatusesHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/batches"] = NewGetBatches(o.context, o.GetBatchesHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/batches/{batch_id}"] = NewGetBatchesBatchID(o.context, o.GetBatchesBatchIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/blocks"] = NewGetBlocks(o.context, o.GetBlocksHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/blocks/{block_id}"] = NewGetBlocksBlockID(o.context, o.GetBlocksBlockIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/peers"] = NewGetPeers(o.context, o.GetPeersHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/receipts"] = NewGetReceipts(o.context, o.GetReceiptsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/state"] = NewGetState(o.context, o.GetStateHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/state/{address}"] = NewGetStateAddress(o.context, o.GetStateAddressHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/status"] = NewGetStatus(o.context, o.GetStatusHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/transactions"] = NewGetTransactions(o.context, o.GetTransactionsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/transactions/{transaction_id}"] = NewGetTransactionsTransactionID(o.context, o.GetTransactionsTransactionIDHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/batch_statuses"] = NewPostBatchStatuses(o.context, o.PostBatchStatusesHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/batches"] = NewPostBatches(o.context, o.PostBatchesHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/receipts"] = NewPostReceipts(o.context, o.PostReceiptsHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *SawtoothRESTAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *SawtoothRESTAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *SawtoothRESTAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *SawtoothRESTAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
