// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Sawtooth REST API
_This HTTP pragmatic REST API is built on top of Sawtooth's
existing ZMQ/Protobuf infrastructure, simplifying client
interaction with the blockchain by exposing endpoints that
use common HTTP/JSON standards._



    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.8.0

    Consumes:
    - application/json
    - application/octet-stream

    Produces:
    - application/json

swagger:meta
*/
package restapi
