// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// BatchHeader batch header
// swagger:model BatchHeader
type BatchHeader struct {

	// signer public key
	SignerPublicKey string `json:"signer_public_key,omitempty"`

	// transaction ids
	TransactionIds []string `json:"transaction_ids"`
}

// Validate validates this batch header
func (m *BatchHeader) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BatchHeader) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BatchHeader) UnmarshalBinary(b []byte) error {
	var res BatchHeader
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
