// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// BlockHeader block header
// swagger:model BlockHeader
type BlockHeader struct {

	// batch ids
	BatchIds []string `json:"batch_ids"`

	// block num
	BlockNum int64 `json:"block_num,omitempty"`

	// consensus
	// Format: binary
	Consensus io.ReadCloser `json:"consensus,omitempty"`

	// previous block id
	PreviousBlockID string `json:"previous_block_id,omitempty"`

	// signer public key
	SignerPublicKey string `json:"signer_public_key,omitempty"`

	// state root hash
	StateRootHash string `json:"state_root_hash,omitempty"`
}

// Validate validates this block header
func (m *BlockHeader) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BlockHeader) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BlockHeader) UnmarshalBinary(b []byte) error {
	var res BlockHeader
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
