// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Link link
// swagger:model Link
type Link string

// Validate validates this link
func (m Link) Validate(formats strfmt.Registry) error {
	return nil
}
