// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TransactionHeader transaction header
// swagger:model TransactionHeader
type TransactionHeader struct {

	// batcher public key
	BatcherPublicKey string `json:"batcher_public_key,omitempty"`

	// dependencies
	Dependencies []string `json:"dependencies"`

	// family name
	FamilyName string `json:"family_name,omitempty"`

	// family version
	FamilyVersion string `json:"family_version,omitempty"`

	// inputs
	Inputs []string `json:"inputs"`

	// nonce
	Nonce string `json:"nonce,omitempty"`

	// outputs
	Outputs []string `json:"outputs"`

	// payload sha512
	PayloadSha512 string `json:"payload_sha512,omitempty"`

	// signer public key
	SignerPublicKey string `json:"signer_public_key,omitempty"`
}

// Validate validates this transaction header
func (m *TransactionHeader) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TransactionHeader) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransactionHeader) UnmarshalBinary(b []byte) error {
	var res TransactionHeader
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
